# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d556768fde11603a259a69f4894d96baeddee2545a2028823b1de1cfd04060574624b5cea62c3b84faeafc8ace9f6845fa90bdf2d5535a2819332895d102e756

test:
  secret_key_base: 001de3385c98a66845f493c18a0e0eda47d1e05b2eb552426494b387a0b0122d102669d2efa09eda6d762a994d8d852431cf35631326ceb98e661f6c78c98baa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
